name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build Go application
      run: go build -v ./...

    - name: Run tests
      run: go test -coverprofile=test-coverage.out -v ./... | tee test-results.txt

    - name: Generate tests coverage
      run: go tool cover -func=test-coverage.out | tee test-coverage.txt

    - name: Upload test & coverage results as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results.txt
          test-coverage.txt
          test-coverage.out

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine Docker tag
      id: vars
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
        fi

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }} .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }}
